name: Node.js CI Development Server Action Runner

on:
  push:
    branches: [development]

jobs:
  install:
    runs-on: development-server

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: npm install and restart server
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install
      - run: pm2 restart app-backend
